### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by yuvadm** [eyelight/glasnostr#2]
Any reason not to have support for multithreading?

**Comment by eyelight** [comment]
When I was initially testing, there were eleven identical processes working simultaneously in my process manager after a single invocation (linux/amd64). That made me believe that the compiler was analyzing/optimizing and the runtime was allowing the loop to become concurrent under the hood, so, I left everything synchronous. I'm open to being wrong & adding multiple routines explicitly 🤙🏼

**Comment by denis2342** [comment]
one process starts one thread, so you're wrong! ;)

**Comment by eyelight** [comment]
https://github.com/eyelight/glasnostr/releases/tag/v0.0.3
